spring:
  devtools:
    restart:
      enabled: true

  application:
    name: schedule
  datasource:
    url: jdbc:mysql://localhost:3306/schedule?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "123"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # create-drop, create, update, validate, none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


api:
  prefix: /api/v1


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

logging:
  level:
    com.ptit.schedule: DEBUG


#logging:
#  level:
#    org:
#        hibernate:
#          SQL: DEBUG
#          type:
#              descriptor.sql.BasicBinder: TRACE
#        springframework:
#          orm:
#            jpa: DEBUG
#          transaction: DEBUG